# 图片验证码有效时长(秒)
IMAGE_CODE_EXPIRES_SECONDS = 120

# 手机验证码有效时长(秒)
SMS_CODE_EXPIRES_SECONDS  = 300

# 区域信息缓存有效时长(秒)
AREA_INFO_REDIS_EXPIRES_SECONDS = 86400

# 主页房屋展示最大数量
HOME_PAGE_MAX_HOUSES = 5

# 房源列表页每页显示房屋数目
HOUSE_LIST_PAGE_CAPACITY = 3